name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const commitTypes = new Set(commits.data
              .map(commit => commit.commit.message.split(':')[0].toLowerCase().trim())
              .filter(type => ['feat', 'fix', 'chore'].includes(type)));
            
            const labelsToAdd = Array.from(commitTypes).map(type => {
              switch(type) {
                case 'feat': return 'feature';
                case 'fix': return 'bug';
                case 'chore': return 'chore';
                default: return type;
              }
            });
            
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }
